# Accesstoken - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YTM4NzQ5ZmM5NDljYzhhYjU1Y2JmOSIsImlhdCI6MTcyMTk5MzAzM30._XFJfboeTeXmJM36qTCnmVWd-xW8gcu24WW3e86eBn4

# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname": "John",
#     "email": "john2@gmail.com",
#     "password": "John@123"
# }

GET http://localhost:3000/trending-blogs
