# Accesstoken - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YTM4NzQ5ZmM5NDljYzhhYjU1Y2JmOSIsImlhdCI6MTcyMTk5MzAzM30._XFJfboeTeXmJM36qTCnmVWd-xW8gcu24WW3e86eBn4

# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname": "John",
#     "email": "john2@gmail.com",
#     "password": "John@123"
# }

# POST http://localhost:3000/get-blog
# Content-Type: application/json

# {
#     "blog_id": "CETY4jwemeHaeGNkOSyzRBdO"
# }

# POST http://localhost:3000/get-profile
# Content-Type: application/json

# {
#     "username": "shardull"
# }



# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YTRlZTA5NmY3MzkxNTY2Zjg5YmE0MSIsImlhdCI6MTcyNTEwNDc2NX0.uqVJ2zEXDbzPKbZySy5xw96G6_K5uUlE9JPdPKy2XJE

# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email" : "Yash@gmail.com",
#     "password" : "Yash@123"
# }


// change password
# POST http://localhost:3000/change-password
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YTRlZTA5NmY3MzkxNTY2Zjg5YmE0MSIsImlhdCI6MTcyNTEwNDc2NX0.uqVJ2zEXDbzPKbZySy5xw96G6_K5uUlE9JPdPKy2XJE

# {
#     "currentPassword" : "Yash@1234",
#     "newPassword" : "Yash@123"
# }


// sigin after changed password
# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email" : "Yash@gmail.com",
#     "password" : "Yash@123"
# }











// new-notification

# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email" : "yash@gmail.com",
#     "password" : "Yash@123"
# }



GET http://localhost:3000/new-notification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YTRlZTA5NmY3MzkxNTY2Zjg5YmE0MSIsImlhdCI6MTcyNTE4NDAxNH0.65iWHo14wdYrCh0CkcVTCCBARi5ZaJzPT_Ec_qcWTlo